### ISSUE TITLE
Invalid data structure for contact data

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-data-w3c#4]
We get this structure on `contributor.person.contact`:

https://github.com/relaton/relaton-data-w3c/blob/4b76f4676a7160a0bebbf802cec3351ec626e44f/data/soap11.yaml#L44-L46

However, the model defines this: https://github.com/relaton/relaton-models/blob/main/models/ContactMethod.lutaml

Basically, we should expect this instead:

```yaml
contact:
- email: "..."
```

**Comment by strogonoff** [comment]
This is not so urgent now at least for BibXML service (it now normalizes loose YAML).

**Comment by opoudjis** [comment]
Yeah, in the RNC:

````
email = element email { text }
````

**Comment by ronaldtse** [comment]
@andrew2net need your help here, thanks!

**Comment by andrew2net** [comment]
fixed in relaton-bib v 1.12.2 but we've removed the static dataset https://github.com/relaton/relaton-data-w3c/issues/5#issuecomment-1185176169
The contact information was only in the static dataset. The W3C RDF source doesn't provide contact information.
