### ISSUE TITLE
(URGENT) Missing contributor information: contact, affiliation

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-w3c#6]
In W3C REC-xpath-19991116, the website provides:
https://www.w3.org/TR/1999/REC-xpath-19991116/
<img width="668" alt="Screenshot 2022-07-15 at 10 11 48 AM" src="https://user-images.githubusercontent.com/11865/179126778-659367ff-3857-486d-bf9d-0efacc272124.png">

But the affiliation and email information are not captured in the YAML:
https://github.com/relaton/relaton-data-w3c/blob/7065f93e8e1ec197c0cd41b394e83c75eb4525c9/data/rec-xpath-19991116.yaml#L18-L38

**Comment by andrew2net** [comment]
@ronaldtse in the RDF source we don't have affiliation information:
```xml
    <REC rdf:about="https://www.w3.org/TR/1999/REC-xpath-19991116/">
        <dc:date>1999-11-16</dc:date>
        <dc:title>XML Path Language (XPath) Version 1.0</dc:title>
        <doc:obsoletes rdf:resource="https://www.w3.org/TR/1999/PR-xpath-19991008"/>
        <doc:versionOf rdf:resource="https://www.w3.org/TR/xpath/"/>
        <editor rdf:parseType="Resource">
            <contact:fullName>James Clark</contact:fullName>
        </editor>
        <editor rdf:parseType="Resource">
            <contact:fullName>Steven DeRose</contact:fullName>
        </editor>
        <org:deliveredBy rdf:parseType="Resource">
            <contact:homePage rdf:resource="https://www.w3.org/XML/Group/Linking"/>
        </org:deliveredBy>
        <mat:hasErrata rdf:resource="https://www.w3.org/1999/11/REC-xpath-19991116-errata"/>
    </REC>
```

**Comment by ronaldtse** [comment]
@andrew2net darn it 😮‍💨 Thanks.

**Comment by ronaldtse** [comment]
I've posted an issue here: https://github.com/ietf-ribose/bibxml-service/issues/235

**Comment by ronaldtse** [comment]
The linked issue is closed -- W3C does not provide contributor contact or affiliation information via W3C API. We will have to scrape if we need this information. Closing for now.
