### ISSUE TITLE
(URGENT) W3C identifiers not found

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-w3c#7]
```
[relaton-w3c] ("W3C CR-rdf-schema-20000327") not found.
[relaton-w3c] ("W3C NOTE-SOAP-20000508") not found.
[relaton-w3c] ("W3C NOTE-p3p-rdfschema-20020125") not found.
[relaton-w3c] ("W3C NOTE-xkms-20010330") not found.
[relaton] (W3C WD-soap12-part1-20020626) not found.
[relaton-w3c] ("W3C WD-soap12-part1-20020626") not found.
[relaton-w3c] ("W3C WD-soap12-part2-20020626") not found.
[relaton-w3c] ("W3C WD-xml-2e-20000814") not found.
[relaton-w3c] ("W3C WD-xmldsig-core-20001012") not found.
[relaton-w3c] ("W3C WD-xmlenc-core-20011018") not found.
[relaton] (W3C REC-xpath-19991116) not found.
```

## Available in relaton-data-w3c

https://github.com/relaton/relaton-data-w3c/blob/main/data/note-soap-20000508.yaml
https://github.com/relaton/relaton-data-w3c/blob/main/data/note-p3p-rdfschema-20020125.yaml
https://github.com/relaton/relaton-data-w3c/blob/main/data/note-xkms-20010330.yaml
https://github.com/relaton/relaton-data-w3c/blob/main/data/wd-soap12-part1-20020626.yaml
https://github.com/relaton/relaton-data-w3c/blob/main/data/wd-soap12-part2-20020626.yaml
https://github.com/relaton/relaton-data-w3c/blob/main/data/rec-xpath-19991116.yaml

## Not available in relaton-data-w3c

```
[relaton-w3c] ("W3C CR-rdf-schema-20000327") not found.
[relaton-w3c] ("W3C WD-xml-2e-20000814") not found.
[relaton-w3c] ("W3C WD-xmldsig-core-20001012") not found.
[relaton-w3c] ("W3C WD-xmlenc-core-20011018") not found.
```

For the last two, the closest documents I can find are:
* https://github.com/relaton/relaton-data-w3c/blob/main/data/rec-xmldsig-core-20020212.yaml
* https://github.com/relaton/relaton-data-w3c/blob/main/data/rec-xmlenc-core-20021210.yaml

This is blocking https://github.com/ietf-ribose/bibxml-service/issues/231

**Comment by andrew2net** [comment]
@ronaldtse fixed for available documents.

**Comment by ronaldtse** [comment]
Thanks @andrew2net , closing this in favour of #8 for the not-found documents.

I can confirm that except the 4 not-found documents, all the rest can be fetched properly.
